plugins = []
headers = []
redirects = []

[dev]
command = "npm run dev"
targetPort = 3000
port = 8888

[functions]

  [functions."*"]

[build]
publish = "."
publishOrigin = "config"
commandOrigin = "ui"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]