backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "YENC Journal"
    file: "data/post.json" # Pointing exactly to your file in the screenshot
    allow_add: true
    fields:
      - name: posts
        label: Posts
        widget: list
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Category", name: "category", widget: "select", options: ["Leadership", "Education", "Community"] }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Excerpt", name: "excerpt", widget: "text" }
          - { label: "Image URL", name: "image", widget: "string" }
          - { label: "Path", name: "url", widget: "hidden", default: "articles/post.html" }
