backend:
  name: git-gateway
  branch: main # Double check if your GitHub says 'main' or 'master'

media_folder: "images"
public_folder: "/images"

# This makes the dashboard look professional
site_url: https://yencofficial.netlify.app
display_name: YENC Content Manager

collections:
  - name: "blog"
    label: "YENC Journal Posts" # This will show up in your sidebar
    file: "YEN-Calauag/data/articles.json" # Added the folder path here
    allow_add: true
    fields:
      - name: posts
        label: Posts
        widget: list
        fields:
          - { label: "Post ID", name: "id", widget: "string" }
          - { label: "Article Title", name: "title", widget: "string" }
          - { label: "Category", name: "category", widget: "select", options: ["Leadership", "Education", "Community"] }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Short Excerpt", name: "excerpt", widget: "text" }
          - { label: "Image URL", name: "image", widget: "string" }
          - { label: "Path", name: "url", widget: "hidden", default: "articles/post.html" }
